name: ci

on: [push, pull_request]

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v3
              with:
                  node-version: 20
            - name: "install mops"
              run: npm i -g ic-mops

            - name: "check"
              run: make check-strict
            - name: "test"
              run: make test
            - name: "docs"
              run: make docs

            - name: Cache ~/.cabal/store
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cabal/store
                  key: cabal-${{ runner.os }}-${{ hashFiles('gen-tests/*.cabal', 'gen-tests/cabal.project.freeze') }}
                  restore-keys: cabal-${{ runner.os }}-
            - uses: haskell/actions/setup@v2
              with:
                  ghc-version: 9.2.8
                  cabal-version: "3.8"
            - name: Build gen-tests
              run: cd gen-tests; cabal build
            - name: Run gen-tests
              run: cd gen-tests; cabal run gen-tests
