name: release

# until we do releases, deploy docs with every commit to main
on:
    push:
        branches:
            - main
        # tags:
        #   - '*'

jobs:
    generate-docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v3
              with:
                  node-version: 20
            - name: "install mops"
              run: npm i -g ic-mops
            - name: "docs"
              run: make docs
            - name: Upload docs
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages # The branch the action should deploy to.
                  FOLDER: docs/ # The folder the action should deploy.
